[package]
authors = ["Mark Simulacrum <mark.simulacrum@gmail.com>"]
build = "build.rs"
categories = ["development-tools"]
description = "Bisects rustc toolchains with rustup"
keywords = ["rustup"]
license = "MIT OR Apache-2.0"
name = "cargo-bisect-rustc"
readme = "README.md"
repository = "https://github.com/rust-lang-nursery/cargo-bisect-rustc"
version = "0.1.0"

[dependencies]
dialoguer = "0.3.0"
dirs = "2.0"
env_logger = "0.6.0"
failure = "0.1"
flate2 = "1.0.1"
git2 = "0.8"
log = "0.4"
pbr = "1.0.0"
reqwest = "0.9"
structopt = "0.2.5"
tar = "0.4"
tee = "0.1"
tempdir = "0.3.6"
toml = "0.4"
xz2 = "0.1.3"
chrono = "0.4.0"

[dev-dependencies]
quickcheck = "0.7"
